### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '~/DeepGlycanSite/src/unimol_tools/weights/mol_pre_all_h_220816.pt'

### ISSUE THREAD

**Issue by sivanr92** [xichengeva/DeepGlycanSite#1]
Did I miss something? I could not find this file in the weights/ folder, either. 

MDAnalysis=2.4.3 did not work. I had to change it to the latest version (2.7.0).

I couldn't complete the example run itself. Any help would be appreciated.

**Comment by Xinheng-He** [comment]
Hi, as written in the README file:

If auto-download fails, you can also download the checkpoints from https://huggingface.co/Xinheng/DeepGlycanSite/tree/main or https://zenodo.org/records/10065607, just put rec_only.ckpt and with_ligand.ckpt to ./ckpt, and mol_pre_all_h_220816.pt to ./src/unimol_tools/weights

BTW, any version of MDAnalysis later should be ok. On my machine, 2.4.3 works.
