### ISSUE TITLE
peg-lib issue

### ISSUE THREAD

**Issue by SupanthaDey9** [xichengeva/DeepGlycanSite#11]
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.0.1 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3,!=3.4.*,<3.9; 1.1.0 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.9; 1.1.1 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.9; 1.7.1 Requires-Python >=3.10; 2024.6.20 Requires-Python >=3.10; 3.3 Requires-Python >=3.10; 3.3rc0 Requires-Python >=3.10; 8.19.0 Requires-Python >=3.10; 8.20.0 Requires-Python >=3.10; 8.21.0 Requires-Python >=3.10; 8.22.0 Requires-Python >=3.10; 8.22.1 Requires-Python >=3.10; 8.22.2 Requires-Python >=3.10; 8.23.0 Requires-Python >=3.10; 8.24.0 Requires-Python >=3.10; 8.25.0 Requires-Python >=3.10; 8.26.0 Requires-Python >=3.10

keep getting this error after running environment.yml file

also the manual process as well

ERROR: Could not find a version that satisfies the requirement pyg-lib (from versions: none)
ERROR: No matching distribution found for pyg-lib

failed

CondaEnvException: Pip failed

**Comment by Mengo-ye** [comment]
I also encountered this problem, looking forward to the solution, thank you.

**Comment by Xinheng-He** [comment]
Well, maybe you can try to install other packages. Then install pyg following the official repo
https://pytorch-geometric.readthedocs.io/en/latest/
