### ISSUE TITLE
Several Errors Trying to Install

### ISSUE THREAD

**Issue by ColinXD** [xichengeva/DeepGlycanSite#13]
I will preface this by saying I am very new to installing software with Python. I am trying to install with GOU and I keep coming across errors. The first thing I do is run the cloning of the environment, and then I just copy and paste the code under GPU installation, and this gives me many errors. I will share all the output below. Any help would be greatly appreciated, thank you.
[DGSOutput.txt](https://github.com/user-attachments/files/16513395/DGSOutput.txt)

**Comment by Xinheng-He** [comment]
HI, please install it in linux environment. Also I suggest you to wait for our server version~

**Comment by ColinXD** [comment]
I was wondering when you predict the server version might be available by?

**Comment by Xinheng-He** [comment]
In planning, if possible, you can send me or Xi the protein you want to predict. We are happy to provide help.
