### ISSUE TITLE
prepare training data still have problem

### ISSUE THREAD

**Issue by Mengo-ye** [xichengeva/DeepGlycanSite#14]
Could you please provide guidance on how to properly prepare my own training data?  Any specific steps, tools, or considerations would be greatly appreciated.

**Comment by Xinheng-He** [comment]
You can just refer to the way we deal with test data in the py file.

**Comment by Mengo-ye** [comment]
@Xinheng-He I don't understand.

**Comment by Xinheng-He** [comment]
We'll provide it later.

**Comment by Mengo-ye** [comment]
Thanks, I appreciate your help.
