### ISSUE TITLE
示例测试出现问题

### ISSUE THREAD

**Issue by gky2023** [xichengeva/DeepGlycanSite#2]
你好！我在执行python single_case_prediction.py --conf P2Y14_example/hparams_rec.yaml  --ckpt_path ckpts/rec_only.ckpt --input_fn P2Y14_example/P2Y14_AF.pdb  --out_path P2Y14_example/ --output_fn P2Y14_af.txt
出现如下报错，请问是什么原因？
![QQ图片20240626135110](https://github.com/xichengeva/DeepGlycanSite/assets/130385026/fc93c6ff-e9a9-45ec-9b90-4866b7033411)

**Comment by Xinheng-He** [comment]
Hi, please refer to the closed issue 1 or the following description, you did not download the ckpt file for unimol.

If auto-download fails, you can also download the checkpoints from https://huggingface.co/Xinheng/DeepGlycanSite/tree/main or https://zenodo.org/records/10065607, just put rec_only.ckpt and with_ligand.ckpt to ./ckpt, and mol_pre_all_h_220816.pt to ./src/unimol_tools/weights
