### ISSUE TITLE
Dataset for Retraining

### ISSUE THREAD

**Issue by jozhang97** [xichengeva/DeepGlycanSite#3]
Hi,

Thanks a lot for the great work!

I'm interested in re-training DeepGlycanSite but I'm not very familiar with your data processing pipeline discussed [here](https://github.com/xichengeva/DeepGlycanSite?tab=readme-ov-file#dataset)

Do you have plans to release entries at `data/PDBBind_processed` or scripts that process the raw pdb/carbohydrate ids into the necessary format for training?

**Comment by Xinheng-He** [comment]
We are preparing for it, once finished, we'll release it as a dataset.
You can now use the testing script to prepare the pdb ids for training, that's not too complex.

**Comment by Mengo-ye** [comment]
Hello, I'm having trouble understanding how to prepare the training data.
