### ISSUE TITLE
Problems with numpy version

### ISSUE THREAD

**Issue by ProtoQSAR** [xichengeva/DeepGlycanSite#6]
numpy installation gives me an error:
'''
(DeepGlycanSite) F:\DeepGlycanSite>pip install numpy==1.21.0
Collecting numpy==1.21.0
  Downloading numpy-1.21.0-cp39-cp39-win_amd64.whl.metadata (2.0 kB)
Downloading numpy-1.21.0-cp39-cp39-win_amd64.whl (14.0 MB)
   ---------------------------------------- 14.0/14.0 MB 17.2 MB/s eta 0:00:00
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.9.0 requires numpy>=1.23, but you have numpy 1.21.0 which is incompatible.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 1.21.0 which is incompatible.
Successfully installed numpy-1.21.0
'''

Can you indicate me the version of matplotlib  and scipy that you are using?

**Comment by Xinheng-He** [comment]
Well, 1.21.0 is from a suggestion. I think it should works with matplotlib 3.9.0 and scipy 1.13.1, it's not a too big change from 1.21.0 to 1.22.4 or 1.23. But in your case, I think to use 1.23 is ok.
