### ISSUE TITLE
Bad input .sdf file

### ISSUE THREAD

**Issue by gky2023** [xichengeva/DeepGlycanSite#8]
Hello, I added hydrogen atoms to my small molecule as required using DS software, but encountered the following error. Could you please advise on the cause? Looking forward to your reply.
![1](https://github.com/xichengeva/DeepGlycanSite/assets/130385026/4401e995-7323-4d39-bcde-419668ab2b3e)
![2](https://github.com/xichengeva/DeepGlycanSite/assets/130385026/99219081-4483-467d-9765-b4d9d2fbd1c8)

**Comment by Xinheng-He** [comment]
You should try to make your molecule readable by RDkit.

**Comment by Xinheng-He** [comment]
It looks ok, but you can try to clean hydrogens firstly and then add it by rdkit.
